package helperclasses;

/**
 * Created by espen on 14.03.14.
 */
public enum Request {
    APPOINTMENTSOFUSER,
    ALARMOFAPPOINTMENT,
    DATEOFAPPOINTMENT,
    TIMEOFAPPOINTMENT,
    DESCRIPTIONOFAPPOINTMENT,
    LISTOFAPPOINTMENTSFORNOTIFICATIONSOFUSER,
    FROMDATE, FROMTIME,
    PARTICIPANTSOFAPPOINTMENT,
    OWNEROFAPPOINTMENT,
    GETAPPOINTMENT;


}
