package helperclasses;

/**
 * Created by Wien on 13.03.14.
 */
public enum Requests {
    APPOINTMENTSOFUSER,
    ALARMOFAPPOINTMENT,
    DATEOFAPPOINTMENT,
    TIMEOFAPPOINTMENT,
    DESCRIPTIONOFAPPOINTMENT,
    LISTOFAPPOINTMENTSFORNOTIFICATIONSOFUSER,
    FROMDATE, FROMTIME,
    PARTICIPANTSOFAPPOINTMENT,
    OWNEROFAPPOINTMENT
    ;
}
