package helperclasses;

/**
 * Created by espen on 14.03.14.
 */
public enum Request {
    ALARMOFAPPOINTMENT,
    PARTICIPANTSOFAPPOINTMENT,
    ADDAPPOINTMENT,
    LOGOUT,
    LOGIN,
    GETUSERS,
    UPDATEAPPOINTMENT,
    APPOINTMENTSWHEREUSERISOWNER,
    APPOINTMENTSWHEREUSERISPARTICIPANT,
    UPDATEPARTICIPANTSTATUS,
    GETLOGGEDINUSER,
    GETSTATUSFORAPPOINTMENT;
}
